# Generated by Django 4.2.3 on 2023-07-30 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_estudios', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Entregable',
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='bio',
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='dni',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='telefono',
            field=models.IntegerField(),
        ),
    ]
